default:
  mongo: 'mongodb://localhost:27017'
  dsn: false
  #All operation intervals are in minutes
  indexInterval: 5
  deletionGracePeriod: 1440
  deletionOperationInterval: 30
  updateIconsInterval: 30
  logLevel: 'debug'
development:
  mongo: 'mongodb://rnettest:rNet01test@db01.rnet.cf:27017/rnettest'
production:
  logLevel: 'info'

